"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.showInformationWithActionsImpl = exports.showInformation = exports.showWarningWithActionsImpl = exports.showWarning = exports.showErrorWithActionsImpl = exports.showError = void 0;
const showError = (conn) => (s) => () => conn.window.showErrorMessage(s);
exports.showError = showError;
const showErrorWithActionsImpl = (conn) => (s) => (actions) => () => conn.window.showErrorMessage(s, ...actions);
exports.showErrorWithActionsImpl = showErrorWithActionsImpl;
const showWarning = (conn) => (s) => () => conn.window.showWarningMessage(s);
exports.showWarning = showWarning;
const showWarningWithActionsImpl = (conn) => (s) => (actions) => () => conn.window.showWarningMessage(s, ...actions);
exports.showWarningWithActionsImpl = showWarningWithActionsImpl;
const showInformation = (conn) => (s) => () => conn.window.showInformationMessage(s);
exports.showInformation = showInformation;
const showInformationWithActionsImpl = (conn) => (s) => (actions) => () => conn.window.showInformationMessage(s, ...actions);
exports.showInformationWithActionsImpl = showInformationWithActionsImpl;
