"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.error = exports.warn = exports.info = exports.log = void 0;
const log = (conn) => (s) => () => conn.console.log(s);
exports.log = log;
const info = (conn) => (s) => () => conn.console.info(s);
exports.info = info;
const warn = (conn) => (s) => () => conn.console.warn(s);
exports.warn = warn;
const error = (conn) => (s) => () => conn.console.error(s);
exports.error = error;
