"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createTextDocument = exports.positionAtOffset = exports.offsetAtPosition = exports.getLineCount = exports.getVersion = exports.getLanguageId = exports.getUri = exports.getTextAtRange = exports.getText = void 0;
const vscode_languageserver_textdocument_1 = require("vscode-languageserver-textdocument");
const getText = (document) => () => document.getText();
exports.getText = getText;
const getTextAtRange = (document) => (range) => () => document.getText(range);
exports.getTextAtRange = getTextAtRange;
const getUri = (document) => document.uri;
exports.getUri = getUri;
const getLanguageId = (document) => document.languageId;
exports.getLanguageId = getLanguageId;
const getVersion = (document) => () => document.version;
exports.getVersion = getVersion;
const getLineCount = (document) => () => document.lineCount;
exports.getLineCount = getLineCount;
const offsetAtPosition = (document) => (pos) => () => document.offsetAt(pos);
exports.offsetAtPosition = offsetAtPosition;
const positionAtOffset = (document) => (offset) => () => document.positionAt(offset);
exports.positionAtOffset = positionAtOffset;
const createTextDocument = (uri) => (languageId) => (version) => (content) => () => vscode_languageserver_textdocument_1.TextDocument.create(uri, languageId, version, content);
exports.createTextDocument = createTextDocument;
